### ISSUE TITLE
document.createElement doesn't work in IE11

### ISSUE THREAD

**Issue by WebrealizerZS** [WebReflection/custom-elements#1]
I was trying this new version and I couldn't make it work in IE11 when the same code works with the old polyfill. 

Files I have used to reproduce a problem:
https://gist.github.com/WebrealizerZS/e7bce5618395e23f4fe5f0daeb8e6d60

IE11 breaks with a message:
```
newCustomElements.html
SCRIPT438: Object doesn't support property or method 'hello'
newCustomElements.html (28,3)
```

But it works fine with the old polyfill.

**Comment by WebrealizerZS** [comment]
Babel 7.8.3 is used 

```json
    "@babel/cli": "^7.8.3",
    "@babel/core": "^7.8.3",
    "@babel/node": "^7.10.3",
    "@babel/plugin-transform-modules-umd": "7.2.0",
    "@babel/preset-env": "^7.8.3",
```

.babelrc
```
{
        "sourceMap": true,
	"presets": ["@babel/preset-env"],				}
	"plugins": ["@babel/plugin-transform-modules-umd"]
}

**Comment by WebReflection** [comment]
this page works on IE11:
https://webreflection.github.io/custom-elements-no-builtin/test/?ok

and so does this:
https://webreflection.github.io/custom-elements/test/?ok

accordingly, I don't know why your test is failing.

This is the [source file](https://github.com/WebReflection/custom-elements/blob/master/test/es.js), transpiled into [this file](https://github.com/WebReflection/custom-elements/blob/master/test/index.js), which is loaded through [the index](https://github.com/WebReflection/custom-elements/blob/master/test/index.html).

Everything is tested in IE11 too so ... flagging this as invalid, until more details are provided.

**Comment by WebrealizerZS** [comment]
Hey Andrea! I slightly modified my [gist ](https://gist.github.com/WebrealizerZS/e7bce5618395e23f4fe5f0daeb8e6d60) based on your test  script. You should be able to reproduce the issue right now.

1. Try adding custom method [`hello`](https://gist.github.com/WebrealizerZS/e7bce5618395e23f4fe5f0daeb8e6d60#file-test-m-js-L16) in the custom element Class.
2. Try calling this method after [creating an instance](https://gist.github.com/WebrealizerZS/e7bce5618395e23f4fe5f0daeb8e6d60#file-testpolyfill-html-L18) `let el =document.createElement('custom-element'); el.hello()`;
3. Observe it is failing in IE11.  `Object doesn't support property or method 'hello'`

Let me know if you can reproduce it or not.

**Comment by WebrealizerZS** [comment]
@WebReflection Did you have a chance to look at that? it seems to be a valid issue. I hope we would have a chance to use it in production before we drop IE11. But it might not be ready just yet.

**Comment by WebReflection** [comment]
Uhm ... I can reproduce this indeed ... and I was on vacation, sorry for the delay, looking into it.

**Comment by WebReflection** [comment]
OK, this should've been fixed. Please bear in mind `connectedCallback` might be asynchronous, and since my current test changes the `innerHTML` on `connectedCallback`, if you invoke a method right before you might not see the change applied.

In the real-world, I believe your use case has no meaning, 'cause if you have a method that inject code, it's either in `connectedCallback` or in such method, so nothing breaks anymore in IE11 (updated tests too) but you gotta find a better way to inject your code 😉
