### ISSUE TITLE
Throws TypeError: Illegal constructor when class is proxied 

### ISSUE THREAD

**Issue by ErikGrimes** [WebReflection/custom-elements#2]
```
const proxies = new WeakMap();

function proxy() {
  return function _decorate(target) {
    let proxy = proxies.get(target);
    if (!proxy) {
      proxy = new Proxy(target, {
        construct(base, args, extended) {
          return Reflect.construct(base, args, extended);
        }
      });
    }
    return proxy;
  };
}

@proxy()
export class ProxyTargetElement extends HTMLElement {
  static get TAG() {
    return 'proxy-target';
  }
}

customElements.define(ProxyTargetElement.TAG, ProxyTargetElement);

```

Browser: Safari 14.0
Version: 0.1.9

**Comment by WebReflection** [comment]
AFAIK Proxy and DOM don't work well together in general, but since proxies are undetectable, I'm afraid there's nothing I can do to even try improving the situation.

**Comment by WebReflection** [comment]
P.S. what you could try is to return the proxied element in the constructor without proxying the whole class and its initialization.

**Comment by ErikGrimes** [comment]
I appreciate your looking at this so quickly.  I'm honestly surprised to didn't run into issues sooner.   I'm using the proxy approach to provide inject dependencies into custom element constructors, but I should be able to use the same effect by having a decorator apply a mixin instead of creating a proxy.

**Comment by WebReflection** [comment]
> I appreciate your looking at this so quickly

we're using this in production and any issue is an instant red alert to me 😉

> I should be able to use the same effect by having a decorator apply a mixin instead of creating a proxy.

yup, I strongly suggest to keep Proxies *away* from anything DOM related, as proxied nodes throws error, and proxied constructors are impossible to filter/change in behaviors
