### ISSUE TITLE
HTMLLIElement should be HTMLBRElement here ?

### ISSUE THREAD

**Issue by kapouer** [WebReflection/custom-elements#4]
This feels like a forgotten replacement in last fix:
https://github.com/WebReflection/custom-elements/blob/0acfb63eab710719e84ba8773f0af689f091dbfd/cjs/index.js#L140

**Comment by WebReflection** [comment]
that being said ... you are in the wrong repository

**Comment by WebReflection** [comment]
https://github.com/WebReflection/custom-elements#warning-ungapcustom-elements-is-what-you-are-looking-for
